### ISSUE TITLE
I would make your blog title name a little bigger 

### ISSUE THREAD

**Issue by savvylee11** [xof88/wordpress_fp#1]
I really enjoyed the travel blog look. I would make the title of your blog a little more apparent, because unlike "life sucks" its a really good name! 

I would also work to make your pushpin idea come to life for the future. I know you ran out of time, but the idea of making your site pinterest inspired is a really good idea. Follow that instinct, because it will look amazing if you follow it!

**Comment by xof88** [comment]
Thank you! Love both suggestions and will!
