### ISSUE TITLE
Creating content and resolving navigation bar issue

### ISSUE THREAD

**Issue by jaclynglover** [xof88/wordpress_fp#12]
I really like your site design. It's really simple and beautiful, and showcases your beautiful photos. 

A few suggestions:
- You pointed this out during your presentation, but you could try playing around with your CSS file a bit more to get rid of the gray blocks on your navigation bar. Were you able to use the inspector tool in Chrome to see if you could identify the container class? 
- I know you just launched the site, but you might consider adding content to each of your posts.
- You could consider adding an asterisk to denote which fields are required when people are submitting comments. 

Overall, great job!

**Comment by xof88** [comment]
Thanks so much! 

I did use the inspector tool and identified all the layers around the header (including the header container) and tried changing the colors individually. I could do it but it also changed other parts of the page I didn't want to change. So need to keep playing around with it!

And yes, my goal is to finish writing my posts by the end of August. Wish me luck!

Someone else pointed that out too - I had no idea. I will try to fix tonight.
