### ISSUE TITLE
Links and Intro

### ISSUE THREAD

**Issue by tatyanaberdan** [xof88/wordpress_fp#13]
Awesome job on creating your world map - that's a really cool feature and made me super jealous of your travels! I have two minor recommendations for the site:

- adding links and/or descriptions for the content below the calendar; this way people can get a sense of what each site is and why you recommend it as a resource and can also click easily through all of the pages
-adding an intro to your front page so people know what your site is about and what they can expect to find here 

Again, awesome job!

**Comment by xof88** [comment]
Love both ideas! Will do. Thanks so much!
