### ISSUE TITLE
Feedback!

### ISSUE THREAD

**Issue by mollykorroch** [xof88/wordpress_fp#14]
Life doesn’t suck! ;) Your pictures are great. Really captures the sense of travel and adventure. (Also thank you for teaching me a new word.) Well done on getting the map to work! Very cool. The only real comment I have is to make the heading larger--so perhaps play with some css font size and text spacing? Right now it gets a bit swallowed in the large banner.

**Comment by xof88** [comment]
Totally agree! Thank you! I'll try to update that tonight. And thanks!!
