### ISSUE TITLE
Feedback:) 

### ISSUE THREAD

**Issue by alliefoard** [xof88/wordpress_fp#5]
Hey! 
I was really impressed with what you did to create this travel blog. I especially loved your idea of having the interactive map and hope that one day you can reach your goal of creating that through just code instead the the plug-in. I really liked your idea and your coding of the comment box where people can tell you their favorite places to visit. I think it might be an interesting idea in the future to put pins on the places you are going in the future!

**Comment by xof88** [comment]
Thank you! Great ideas. I hadn't of that last one but like it:) I am going to try it!
