### ISSUE TITLE
Feedback!

### ISSUE THREAD

**Issue by amaliaks** [xof88/wordpress_fp#6]
It was really cool to be able to see all of the places you traveled or are traveling to in the next year! I think something that could help organize your page would to be to put your posts on different pages and label those pages different continents, like Europe, South America, etc.  If you don't want to do that (which makes total sense), I would make the words like Europe, Central America, etc. larger so you can see more of the definition. 

Great site!!

**Comment by xof88** [comment]
Really great idea. Going to do that tonight. Thank you!
